# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: greencaterers

email: 
description: > # this means to ignore newlines until "baseurl:"
  Official website of greencaterers thrissur.One of the best catering and event management in thrissur 
baseurl: greencaterers
url: www.greencaterers.in
twitter_username: greencaterers
github_username:  modernroll
permalink: pretty
author: modernroll
logo: /assets/logo.png
social:
  name: greencaterers
  links:
    - https://www.facebook.com/greencatererstcr
   



# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
gems:
  - jekyll-seo-tag
gems:
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
